### ISSUE TITLE
charge manually a font

### ISSUE THREAD

**Issue by chezsick** [fidergo-stephane-gourichon/digital_video_test_card#1]
hello, you can add option "-f _font_" for changed the font than Vera.ttf

thanks sick!

**Comment by cpcitor** [comment]
Hello. It is possible. Many other things are also possible, I'd like to understand better about the one you suggest.
Why are you interested in adding an option to make easy use of a different font? Isn't Vera a good font? Are you thinking of another font specifically?
Thanks.

**Comment by fidergo-stephane-gourichon** [comment]
Hello. It is possible. Many other things are also possible, I'd like to understand better about the one you suggest.
Why are you interested in adding an option to make easy use of a different font? Isn't Vera a good font? Are you thinking of another font specifically?
Thanks.

**Comment by chezsick** [comment]
is done, this is suggest ok? thank if the option is not set vera is used after if the option is set is use a another font ok.

**Comment by fidergo-stephane-gourichon** [comment]
Implemented in c360122e . Included in latest master branch.
